from django.db import models
from django.contrib.auth.models import User
# Create your models here.
STATUS_CHOICES = (
        (1, 'Active'),
        (0, 'In-Active'),
        )

from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
class UsersManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
        email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        scmuser = ScmUser()
        scmuser.email = email
        scmuser.admin = True
        scmuser.save()
        return user
    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
        email,
        password=password,
        )
        user.staff = True
        user.save(using=self._db)
        scmuser = ScmUser()
        scmuser.email = email
        scmuser.staff = True
        scmuser.save()
        return user
    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
        email,
        password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        scmuser = ScmUser()
        scmuser.email = email
        scmuser.staff = True
        scmuser.save()
        return user


class ScmUser(AbstractBaseUser):
   email=models.CharField(primary_key=True,max_length=300)
   active=models.BooleanField(default=True)
   staff=models.BooleanField(default=False)
   admin=models.BooleanField(default=False)
   time_stamp=models.TimeField(auto_now_add=True)
   USERNAME_FIELD='email'
   REQUIRED_FIELDS=[]
   def get_first_name(self):
      return self.email
   def get_short_name(self):
      return self.email
   def __str__(self):
      return self.email
   def has_perm(self,perm,obj=None):
      return True
   def has_module_perms(self,app_label):
      return True
   @property
   def is_staff(self):
      "Is the user a member of staff?"
      return self.staff
   @property
   def is_admin(self):
      "Is the user a admin member?"
      return self.admin
   @property
   def is_active(self):
      "Is the user active?"
      return self.active
   
   object=UsersManager()
  



class Tenant(models.Model):
    Id = models.IntegerField(primary_key=True)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)

class Channel(models.Model):
    Id = models.IntegerField(primary_key=True)
    TenantId = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)
#trying for this........
class BU(models.Model):
    Id = models.IntegerField(primary_key=True)
    TenantId = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    CreatedDate= models.DateTimeField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)
    channelID=models.ForeignKey(Channel, on_delete=models.CASCADE)

class Division(models.Model):
    Id = models.IntegerField(primary_key=True)
    TenantId = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)

class Category(models.Model):
    Id = models.IntegerField(primary_key=True)
    TenantId = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)

class Brand(models.Model):
    Id = models.IntegerField(primary_key=True)
    TenantId = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)

class Branch(models.Model):
    Id = models.IntegerField(primary_key=True)
    TenantId = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    BUId = models.ForeignKey(BU, on_delete=models.CASCADE)
    channelID=models.ForeignKey(Channel, on_delete=models.CASCADE)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    BranchType = models.CharField(max_length=300,null=True,blank=True)
    TotalVolume = models.CharField(max_length=100,null=True,blank=True)
    TotalArea = models.CharField(max_length=100,null=True,blank=True)
    OperatinHours = models.CharField(max_length=100,null=True,blank=True)
    OpertingDaysoftheWeek = models.CharField(max_length=100,null=True,blank=True)
    operating_times = models.CharField(max_length=100,null=True,blank=True)
    LoadingTimes = models.CharField(max_length=100,null=True,blank=True)
    UnloadingTimes = models.CharField(max_length=100,null=True,blank=True)
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)

class SKU_SNP(models.Model):
    Id = models.IntegerField(primary_key=True)
    TenantId = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    BUId = models.ForeignKey(BU, on_delete=models.CASCADE)
    Code=models.CharField(max_length=300,null=True,blank=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Description=models.TextField()
    UOM = models.CharField(max_length=100,null=True,blank=True)
    CategoryId = models.ForeignKey(Category, on_delete=models.CASCADE)
    DivisionId = models.ForeignKey(Division, on_delete=models.CASCADE)
    Brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    LeadTime = models.CharField(max_length=100,null=True,blank=True)
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)

class Network(models.Model):
    Id = models.IntegerField(primary_key=True)
    SupplyBranch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    SupplyBranchType = models.CharField(max_length=300,null=True,blank=True)
    DemandBranch = models.CharField(max_length=300,null=True,blank=True)
    DemandBranchType = models.CharField(max_length=300,null=True,blank=True)
    DeliveryLeadTime = models.CharField(max_length=300,null=True,blank=True)
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)

class Branch_SKU(models.Model):
    Id = models.IntegerField(primary_key=True)
    BranchId = models.ForeignKey(Branch, on_delete=models.CASCADE)
    SkuId = models.ForeignKey(SKU_SNP, on_delete=models.CASCADE)
    MSL = models.IntegerField(default=None)
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)

class Production_Plant(models.Model):
    Id = models.IntegerField(primary_key=True)
    Name=models.CharField(max_length=300,null=True,blank=True)
    Location=models.CharField(max_length=300,null=True,blank=True)
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)

class Production_Plant_SKU(models.Model):
    Id = models.IntegerField(primary_key=True)
    ProductionPlantId = models.ForeignKey(Production_Plant, on_delete=models.CASCADE)
    SKUId = models.ForeignKey(SKU_SNP, on_delete=models.CASCADE)
    CreatedDate= models.DateField(auto_now_add=True)
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateField(auto_now=True,null=True,blank=True)
    UpdatedBy=models.IntegerField(default=None,blank=True,null=True)
    IPAddress = models.CharField(max_length=300,null=True,blank=True)
    Status=models.IntegerField(choices=STATUS_CHOICES)

class tblForecastDtl(models.Model):
    forecastid=models.IntegerField()
    productid=models.IntegerField()
    Compid=models.IntegerField()
    salesmonth=models.DateField()
    salesYr=models.DateField()
    salesDt=models.DateField()
    statsQty=models.CharField(max_length=200,null=True,blank=True)
    OprtnQty=models.CharField(max_length=250,null=True,blank=True)
    asp=models.CharField(max_length=250,null=True,blank=True)
    abc=models.CharField(max_length=200,null=True,blank=True)
    M0_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M1_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M2_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M3_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M4_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M5_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M6_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M7_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M8_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M8_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M9_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M10_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M11_Qty_3SC=models.CharField(max_length=250,null=True,blank=True)
    M12_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M0_QTY_3SC=models.CharField(max_length=250,null=True,blank=True)
    M1_QTY=models.CharField(max_length=250,null=True,blank=True)
    M2_QTY=models.CharField(max_length=250)
    M3_QTY=models.CharField(max_length=250)
    M4_QTY=models.CharField(max_length=250)
    M5_QTY=models.CharField(max_length=250)
    M6_QTY=models.CharField(max_length=250)
    M7_QTY=models.CharField(max_length=250)
    M8_QTY=models.CharField(max_length=250)
    M9_QTY=models.CharField(max_length=250)
    M10_QTY=models.CharField(max_length=250)
    M11_QTY=models.CharField(max_length=250)
    M12_QTY=models.CharField(max_length=250)
    M6_Avg_Sales=models.CharField(max_length=400,blank=True,null=True)
    M3_Avg_Sales=models.CharField(max_length=400,blank=True,null=True)
    L3M_Qty_Avg=models.CharField(max_length=400,blank=True,null=True)
    LYSM1_Sales=models.CharField(max_length=400,blank=True,null=True)
    LYSM2_Sales=models.CharField(max_length=400,blank=True,null=True)
    LYSM3_Sales=models.CharField(max_length=400,blank=True,null=True)
    LM_Sales=models.CharField(max_length=300,blank=True,null=True)
    L3M_Pri_QTY=models.IntegerField()
    ReasonId=models.IntegerField()
    IsChanged=models.BooleanField(default=False)
    IsApproved=models.BooleanField(default=True)
    SKUStatus=models.BooleanField(default=True)
    CreatedBy=models.CharField(max_length=300,blank=True,null=True)
    CreatedDt=models.DateTimeField(auto_now_add=True)
    UpdatedBy=models.CharField(max_length=400,blank=True,null=True)
    UpdateDt=models.DateTimeField(auto_now_add=True)
    L12Min=models.IntegerField()
    L12Max=models.IntegerField()
    M1=models.CharField(max_length=300,blank=True,null=True)
    M2=models.CharField(max_length=300,blank=True,null=True)
    M3=models.CharField(max_length=300,blank=True,null=True)
    M4=models.CharField(max_length=300,blank=True,null=True)
    M5=models.CharField(max_length=300,blank=True,null=True)
    M6=models.CharField(max_length=300,blank=True,null=True)
    Category=models.CharField(max_length=300,blank=True,null=True)
    Category1=models.CharField(max_length=300,blank=True,null=True)
    Line1=models.CharField(max_length=300,blank=True,null=True)
    Line2=models.CharField(max_length=300,blank=True,null=True)
    Line3=models.CharField(max_length=300,blank=True,null=True)
    Line4=models.CharField(max_length=300,blank=True,null=True)
    SKU=models.ForeignKey(SKU_SNP,on_delete=models.CASCADE)
    Channel=models.ForeignKey(Channel,on_delete=models.CASCADE)
    LocationID=models.IntegerField()

class SalesOrder_Exim_SFTP(models.Model):
    order_no=models.IntegerField()
    Order_Date=models.DateTimeField()
    pick_slip_no=models.IntegerField()
    SHIPPER_Exporter_Name=models.CharField(max_length=300,null=True,blank=True)
    shipper_exporter_address=models.CharField(max_length=600,null=True,blank=True)
    consignee_Name=models.CharField(max_length=300,null=True,blank=True)
    consignee_address=models.CharField(max_length=600,null=True,blank=True)
    warehouse_Code=models.IntegerField()
    warehouse_Name=models.CharField(max_length=400,null=True,blank=True)
    warehouse_address=models.CharField(max_length=600,null=True,blank=True)
    bill_to_Name=models.CharField(max_length=300,null=True,blank=True)
    bill_to_address=models.CharField(max_length=300,null=True,blank=True)
    Exportersref=models.CharField(max_length=300,null=True,blank=True)
    Exportersref=models.CharField(max_length=300,null=True,blank=True)
    others_ref=models.CharField(max_length=300,null=True,blank=True)
    cust_po_no=models.IntegerField()
    cust_po_date=models.DateTimeField()
    gst_invoice_no=models.IntegerField(null=True,blank=True)
    gst_inv_date=models.DateTimeField(auto_now_add=True)
    currency=models.CharField(max_length=400)
    cgst_rate=models.IntegerField()
    cgst_amount=models.FloatField()
    sgst_rate=models.CharField(max_length=400,blank=True,null=True)
    sgst_amount=models.FloatField()
    igst_rate=models.IntegerField()
    igst_amount=models.FloatField()
    tcs_rate=models.IntegerField()
    tcs_amount=models.FloatField(null=True,blank=True)
    invoice_total_amount=models.FloatField(null=True,blank=True)
    invoice_amount_in_words=models.CharField(max_length=600,null=True,blank=True)
    bank_name=models.CharField(max_length=500,null=True,blank=True)
    branch_branch=models.CharField(max_length=600,null=True,blank=True)
    bank_ifsc_code=models.CharField(max_length=400,null=True,blank=True)
    bank_account_no=models.IntegerField(null=True,blank=True)
    ifsc_code=models.CharField(max_length=400,null=True,blank=True)
    micr_code=models.CharField(max_length=500,null=True,blank=True)
    swift_code=models.IntegerField(null=True,blank=True)
    payment_term=models.CharField(max_length=400,null=True,blank=True)
    incoterm=models.CharField(max_length=400,null=True,blank=True)
    shipment_type=models.CharField(max_length=500,null=True,blank=True)
    shipment_mode=models.CharField(max_length=500,null=True,blank=True)
    port_of_loading=models.CharField(max_length=500,null=True,blank=True)
    port_of_discharge=models.CharField(max_length=500,null=True,blank=True)
    country_of_origin=models.CharField(max_length=500,null=True,blank=True)
    state_of_origin=models.CharField(max_length=500,null=True,blank=True)
    district_of_origin=models.CharField(max_length=500,null=True,blank=True)
    final_destination=models.CharField(max_length=500,null=True,blank=True)
    country_of_final_distination=models.CharField(max_length=600,null=True,blank=True)
    pre_carriage_by=models.CharField(max_length=500,null=True,blank=True)
    place_of_receipt_of_pre_carr=models.CharField(max_length=500,null=True,blank=True)
    vassel_flight_no=models.IntegerField(null=True,blank=True)
    adcode=models.CharField(max_length=500,null=True,blank=True)
    totalquantity=models.CharField(max_length=500,null=True,blank=True)
    totalnetweight=models.FloatField(null=True,blank=True)
    totalgrossweight=models.FloatField(null=True,blank=True)
    custom_division=models.FloatField(null=True,blank=True)
    gstin=models.CharField(max_length=500,null=True,blank=True)
    name_of_commissionarate=models.CharField(max_length=500,null=True,blank=True)
    item_code=models.ForeignKey(SKU_SNP,on_delete=models.CASCADE)
    item_description=models.CharField(max_length=700,null=True,blank=True)
    product_category=models.CharField(max_length=300,null=True,blank=True)
    hsn_code=models.IntegerField(null=True,blank=True)
    qty=models.IntegerField(null=True,blank=True)
    product_category=models.CharField(max_length=300,null=True,blank=True)
    uom=models.CharField(max_length=300,null=True,blank=True)
    unit_rate=models.FloatField(null=True,blank=True)
    net_weight=models.IntegerField(null=True,blank=True)
    gross_weight=models.FloatField(null=True,blank=True)
    total_price=models.IntegerField(null=True,blank=True)
    warehousecode=models.IntegerField(null=True,blank=True)
    header_id=models.IntegerField(null=True,blank=True)
    line_id=models.IntegerField(null=True,blank=True)
    delivery_detail_id=models.IntegerField(null=True,blank=True)
    delivery_assignment_id=models.IntegerField(null=True,blank=True)
    delivery_id=models.IntegerField(null=True,blank=True)
    exim_state_origin=models.CharField(max_length=300,null=True,blank=True)
    exim_district_origin=models.CharField(max_length=300,null=True,blank=True)
    consignee_country=models.CharField(max_length=300,null=True,blank=True)
    consignee_tel_no=models.IntegerField(null=True,blank=True)
    ship_to_details=models.CharField(max_length=300,null=True,blank=True)
    export_pincode=models.IntegerField(null=True,blank=True)
    export_country=models.IntegerField(null=True,blank=True)
    buyer_ord_count_date=models.DateTimeField(auto_now_add=True)
    other_ref_count_tel_no=models.IntegerField(blank=True,null=True)
    add_inf_payment_term=models.CharField(max_length=300,blank=True,null=True)
    hdr_status=models.CharField(max_length=100,blank=True,null=True)
    line_status=models.CharField(max_length=100,blank=True,null=True)
    shipping_status=models.CharField(max_length=100,blank=True,null=True)
    order_type=models.CharField(max_length=150,blank=True,null=True)
    reference_type=models.CharField(max_length=100,blank=True,null=True)
    reference_no=models.IntegerField(blank=True,null=True)
    reference_line_no=models.IntegerField()
    custom_exchange_currency=models.CharField(max_length=300,null=True,blank=True)
    custom_exchange_rate=models.CharField(max_length=200,null=True,blank=True)

class FC_Details(models.Model):
    TenantId=models.ForeignKey(Tenant,on_delete=models.CASCADE)
    Forecast_No=models.IntegerField()
    ChannelId=models.ForeignKey(Channel,on_delete=models.CASCADE)
    Channel=models.CharField(max_length=300,null=True,blank=True)
    BUId=models.ForeignKey(BU,on_delete=models.CASCADE)
    BU=models.CharField(max_length=300,null=True,blank=True)
    DivisionId=models.ForeignKey(Division,on_delete=models.CASCADE)
    Division=models.CharField(max_length=300,null=True,blank=True)
    CategoryId=models.ForeignKey(Category,on_delete=models.CASCADE)
    Category=models.CharField(max_length=300,null=True,blank=True)
    BrandId=models.ForeignKey(Brand,on_delete=models.CASCADE)
    Brand=models.CharField(max_length=300,null=True,blank=True)
    SKUId=models.ForeignKey(SKU_SNP,on_delete=models.CASCADE)
    SKU_Code =models.CharField(max_length=300,null=True,blank=True)
    SKU=models.CharField(max_length=300,null=True,blank=True)
    SKU_Class =models.CharField(max_length=20,null=True,blank=True)
    SKU_Status =models.CharField(max_length=50,null=True,blank=True)
    Region=models.CharField(max_length=100,null=True,blank=True)
    AGGREGATE_SPEC1 =models.CharField(max_length=100,null=True,blank=True)
    AGGREGATE_SPEC2 =models.CharField(max_length=100,null=True,blank=True)
    DepoCode=models.CharField(max_length=50,null=True,blank=True)
    ASM= models.CharField(max_length=300,null=True,blank=True)
    LCID=models.IntegerField()
    Launch_Date =models.DateTimeField(auto_now_add=True)
    Launch_PLSIND_State =models.CharField(max_length=100,null=True,blank=True)
    Launch_PLSIND_StateFlag =models.IntegerField(null=True,blank=True)
    ASP=models.IntegerField(null=True,blank=True)
    YTDAvg_Sales =models.IntegerField(null=True,blank=True)
    YTDAvg_Sales_Val =models.IntegerField(default=0,null=True,blank=True)
    Twelve_Mon_Avg_Sales =models.IntegerField(null=True,blank=True)
    Twelve_Mon_Avg_Sales_val =models.IntegerField(default=0,null=True,blank=True)
    Six_Mon_Avg_Sales = models.IntegerField(null=True,blank=True)
    Six_Mon_Avg_Sales_Val =models.IntegerField(null=True,blank=True)
    Three_Mon_Avg_Sales =models.IntegerField(null=True,blank=True)
    Three_Mon_Avg_Sales_val =models.IntegerField(null=True,blank=True)
    LM_Sales =models.IntegerField(null=True,blank=True)
    LM_Sales_Val =models.IntegerField(null=True,blank=True)
    LMFC_Sales =models.IntegerField(null=True,blank=True)
    LMFC_Sales_Val=models.IntegerField(null=True,blank=True)
    LYSM1_Sales =models.IntegerField(null=True,blank=True)
    LYSM2_Sales =models.IntegerField(null=True,blank=True)
    LYSM3_Sales =models.IntegerField(null=True,blank=True)
    LYSM4_Sales =models.IntegerField(null=True,blank=True)
    LYSM5_Sales =models.IntegerField(null=True,blank=True)
    LYSM6_Sales =models.IntegerField(null=True,blank=True)
    LYSM1_Sales_Val =models.IntegerField(null=True,blank=True)
    LYSM2_Sales_Val =models.IntegerField(null=True,blank=True)
    LYSM3_Sales_Val =models.IntegerField(null=True,blank=True)
    LYSM4_Sales_Val =models.IntegerField(null=True,blank=True)
    LYSM5_Sales_Val =models.IntegerField(null=True,blank=True)
    LYSM6_Sales_Val =models.IntegerField(null=True,blank=True)
    YTM_AOP =models.IntegerField(null=True,blank=True)
    YTM_AOP_Val =models.IntegerField(null=True,blank=True)
    YTM_Sales =models.IntegerField(null=True,blank=True)
    YTM_Sales_Val =models.IntegerField(null=True,blank=True)
    LTSF_Sales=models.IntegerField(null=True,blank=True)
    LTSF_Sales_Val=models.IntegerField(null=True,blank=True)
    LYAS_Sales =models.IntegerField(null=True,blank=True)
    LYAS_Sales_Val =models.IntegerField(null=True,blank=True)
    M1_3SC_QTY =models.IntegerField(null=True,blank=True)
    M2_3SC_QTY =models.IntegerField(null=True,blank=True)
    M3_3SC_QTY =models.IntegerField(null=True,blank=True)
    M4_3SC_QTY =models.IntegerField(null=True,blank=True)
    M5_3SC_QTY =models.IntegerField(null=True,blank=True)
    M6_3SC_QTY =models.IntegerField(null=True,blank=True)
    M7_3SC_QTY =models.IntegerField(null=True,blank=True)
    M8_3SC_QTY =models.IntegerField(null=True,blank=True)
    M9_3SC_QTY =models.IntegerField(null=True,blank=True)
    M10_3SC_QTY =models.IntegerField(null=True,blank=True)
    M11_3SC_QTY =models.IntegerField(null=True,blank=True)
    M12_3SC_QTY =models.IntegerField(null=True,blank=True)
    M1_3SC_Val =models.IntegerField(null=True,blank=True)
    M2_3SC_Val =models.IntegerField(null=True,blank=True)
    M3_3SC_Val =models.IntegerField(null=True,blank=True)
    M4_3SC_Val =models.IntegerField(null=True,blank=True)
    M5_3SC_Val =models.IntegerField(null=True,blank=True)
    M6_3SC_Val =models.IntegerField(null=True,blank=True)
    M7_3SC_Val =models.IntegerField(null=True,blank=True)
    M8_3SC_Val =models.IntegerField(null=True,blank=True)
    M9_3SC_Val =models.IntegerField(null=True,blank=True)
    M10_3SC_Val =models.IntegerField(null=True,blank=True)
    M11_3SC_Val =models.IntegerField(null=True,blank=True)
    M12_3SC_Val =models.IntegerField(null=True,blank=True)
    M1_OPS_QTY =models.IntegerField(null=True,blank=True)
    M2_OPS_QTY =models.IntegerField(null=True,blank=True)
    M3_OPS_QTY =models.IntegerField(null=True,blank=True)
    M4_OPS_QTY =models.IntegerField(null=True,blank=True)
    M5_OPS_QTY =models.IntegerField(null=True,blank=True)
    M6_OPS_QTY =models.IntegerField(null=True,blank=True)
    M7_OPS_QTY =models.IntegerField(null=True,blank=True)
    M8_OPS_QTY =models.IntegerField(null=True,blank=True)
    M9_OPS_QTY =models.IntegerField(null=True,blank=True)
    M10_OPS_QTY =models.IntegerField(null=True,blank=True)
    M11_OPS_QTY =models.IntegerField(null=True,blank=True)
    M12_OPS_QTY =models.IntegerField(null=True,blank=True)
    M1_OPS_VAL =models.IntegerField(null=True,blank=True)
    M2_OPS_VAL =models.IntegerField(null=True,blank=True)
    M3_OPS_VAL =models.IntegerField(null=True,blank=True)
    M4_OPS_VAL =models.IntegerField(null=True,blank=True)
    M5_OPS_VAL =models.IntegerField(null=True,blank=True)
    M6_OPS_VAL =models.IntegerField(null=True,blank=True)
    M7_OPS_VAL =models.IntegerField(null=True,blank=True)
    M8_OPS_VAL =models.IntegerField(null=True,blank=True)
    M9_OPS_VAL =models.IntegerField(null=True,blank=True)
    M10_OPS_VAL =models.IntegerField(null=True,blank=True)
    M11_OPS_VAL =models.IntegerField(null=True,blank=True)
    M12_OPS_VAL =models.IntegerField(null=True,blank=True)
    M1_SALES_QTY =models.IntegerField(null=True,blank=True)
    M1_SALES_QTY =models.IntegerField(null=True,blank=True)
    M2_SALES_QTY =models.IntegerField(null=True,blank=True)
    M3_SALES_QTY =models.IntegerField(null=True,blank=True)
    M3_SALES_QTY =models.IntegerField(null=True,blank=True)
    M4_SALES_QTY =models.IntegerField(null=True,blank=True)
    M5_SALES_QTY =models.IntegerField(null=True,blank=True)
    M6_SALES_QTY =models.IntegerField(null=True,blank=True)
    M7_SALES_QTY =models.IntegerField(null=True,blank=True)
    M8_SALES_QTY =models.IntegerField(null=True,blank=True)
    M9_SALES_QTY =models.IntegerField(null=True,blank=True)
    M10_SALES_QTY =models.IntegerField(null=True,blank=True)
    M11_SALES_QTY =models.IntegerField(null=True,blank=True)
    M12_SALES_QTY =models.IntegerField(null=True,blank=True)
    M1_SALES_VAL =models.IntegerField(null=True,blank=True)
    M2_SALES_VAL =models.IntegerField(null=True,blank=True)
    M3_SALES_VAL =models.IntegerField(null=True,blank=True)
    M4_SALES_VAL =models.IntegerField(null=True,blank=True)
    M5_SALES_VAL =models.IntegerField(null=True,blank=True)
    M6_SALES_VAL =models.IntegerField(null=True,blank=True)
    M7_SALES_VAL =models.IntegerField(null=True,blank=True)
    M8_SALES_VAL =models.IntegerField(null=True,blank=True)
    M9_SALES_VAL =models.IntegerField(null=True,blank=True)
    M10_SALES_VAL =models.IntegerField(null=True,blank=True)
    M11_SALES_VAL =models.IntegerField(null=True,blank=True)
    M12_SALES_VAL =models.IntegerField(null=True,blank=True)
    M1_AOP_QTY =models.IntegerField(null=True,blank=True)
    M2_AOP_QTY =models.IntegerField(null=True,blank=True)
    M3_AOP_QTY =models.IntegerField(null=True,blank=True)
    M1_AOP_VAL =models.IntegerField(null=True,blank=True)
    M2_AOP_VAL =models.IntegerField(null=True,blank=True)
    M3_AOP_VAL =models.IntegerField(null=True,blank=True)
    M1_RTF_QTY=models.IntegerField(null=True,blank=True)
    M2_RTF_QTY=models.IntegerField(null=True,blank=True)
    M3_RTF_QTY=models.IntegerField(null=True,blank=True)
    M1_RTF_VAL=models.IntegerField(null=True,blank=True)
    M2_RTF_VAL=models.IntegerField(null=True,blank=True)
    M3_RTF_VAL=models.IntegerField(null=True,blank=True)
    M1_FINALFC_QTY =models.IntegerField(null=True,blank=True)
    M2_FINALFC_QTY =models.IntegerField(null=True,blank=True)
    M3_FINALFC_QTY =models.IntegerField(null=True,blank=True)
    M1_FINALFC_VAL =models.IntegerField(null=True,blank=True)
    M2_FINALFC_VAL =models.IntegerField(null=True,blank=True)
    M3_FINALFC_VAL =models.IntegerField(null=True,blank=True)
    L12_Min =models.IntegerField(null=True,blank=True)
    L12_Max =models.IntegerField(null=True,blank=True)
    L12_Min_VAL =models.IntegerField(null=True,blank=True)
    L12_Max_VAL =models.IntegerField(null=True,blank=True)
    M_1=models.IntegerField(null=True,blank=True)
    M_2=models.IntegerField(null=True,blank=True)
    M_3=models.IntegerField(null=True,blank=True)
    Status=models.CharField(choices=STATUS_CHOICES,max_length=10)
    Six_Mon_Avg_Forecast =models.IntegerField(null=True,blank=True)
    StockTill=models.IntegerField(null=True,blank=True)
    RemarkID=models.IntegerField(null=True,blank=True)
    Remark=models.IntegerField(null=True,blank=True)
    Active=models.CharField(max_length=10)
    Week1_ActualSales =models.IntegerField(null=True,blank=True)
    Week2_ActualSales =models.IntegerField(null=True,blank=True)
    Week3_ActualSales =models.IntegerField(null=True,blank=True)
    Week4_ActualSales =models.IntegerField(null=True,blank=True)
    First_Year =models.IntegerField(null=True,blank=True)
    FY_M1_QTY =models.IntegerField(null=True,blank=True)
    FY_M2_QTY =models.IntegerField(null=True,blank=True)
    FY_M3_QTY =models.IntegerField(null=True,blank=True)
    FY_M4_QTY =models.IntegerField(null=True,blank=True)
    FY_M5_QTY =models.IntegerField(null=True,blank=True)
    FY_M6_QTY =models.IntegerField(null=True,blank=True)
    FY_M7_QTY =models.IntegerField(null=True,blank=True)
    FY_M8_QTY =models.IntegerField(null=True,blank=True)
    FY_M9_QTY =models.IntegerField(null=True,blank=True)
    FY_M10_QTY =models.IntegerField(null=True,blank=True)
    FY_M11_QTY =models.IntegerField(null=True,blank=True)
    FY_M12_QTY =models.IntegerField(null=True,blank=True)
    FY_M1_Val =models.IntegerField(null=True,blank=True)
    FY_M2_Val =models.IntegerField(null=True,blank=True)
    FY_M3_Val =models.IntegerField(null=True,blank=True)
    FY_M4_Val =models.IntegerField(null=True,blank=True)
    FY_M5_Val =models.IntegerField(null=True,blank=True)
    FY_M6_Val =models.IntegerField(null=True,blank=True)
    FY_M7_Val =models.IntegerField(null=True,blank=True)
    FY_M8_Val =models.IntegerField(null=True,blank=True)
    FY_M9_Val =models.IntegerField(null=True,blank=True)
    FY_M10_Val =models.IntegerField(null=True,blank=True)
    FY_M11_Val =models.IntegerField(null=True,blank=True)
    FY_M12_Val =models.IntegerField(null=True,blank=True)
    Second_YEAR =models.IntegerField(null=True,blank=True)
    SY_M1_QTY =models.IntegerField(null=True,blank=True)
    SY_M2_QTY =models.IntegerField(null=True,blank=True)
    SY_M3_QTY =models.IntegerField(null=True,blank=True)
    SY_M4_QTY =models.IntegerField(null=True,blank=True)
    SY_M5_QTY =models.IntegerField(null=True,blank=True)
    SY_M6_QTY =models.IntegerField(null=True,blank=True)
    SY_M7_QTY =models.IntegerField(null=True,blank=True)
    SY_M8_QTY =models.IntegerField(null=True,blank=True)
    SY_M9_QTY =models.IntegerField(null=True,blank=True)
    SY_M10_QTY =models.IntegerField(null=True,blank=True)
    SY_M11_QTY =models.IntegerField(null=True,blank=True)
    SY_M12_QTY =models.IntegerField(null=True,blank=True)
    SY_M1_Val =models.IntegerField(null=True,blank=True)
    SY_M1_Val =models.IntegerField(null=True,blank=True)
    SY_M1_Val =models.IntegerField(null=True,blank=True)
    SY_M2_Val =models.IntegerField(null=True,blank=True)
    SY_M3_Val =models.IntegerField(null=True,blank=True)
    SY_M4_Val =models.IntegerField(null=True,blank=True)
    SY_M5_Val =models.IntegerField(null=True,blank=True)
    SY_M6_Val =models.IntegerField(null=True,blank=True)
    SY_M7_Val =models.IntegerField(null=True,blank=True)
    SY_M8_Val =models.IntegerField(null=True,blank=True)
    SY_M9_Val =models.IntegerField(null=True,blank=True)
    SY_M10_Val =models.IntegerField(null=True,blank=True)
    SY_M11_Val =models.IntegerField(null=True,blank=True)
    SY_M12_Val =models.IntegerField(null=True,blank=True)
    Third_YEAR =models.IntegerField(null=True,blank=True)
    TY_M1_QTY =models.IntegerField(null=True,blank=True)
    TY_M2_QTY =models.IntegerField(null=True,blank=True)
    TY_M3_QTY =models.IntegerField(null=True,blank=True)
    TY_M4_QTY =models.IntegerField(null=True,blank=True)
    TY_M5_QTY =models.IntegerField(null=True,blank=True)
    TY_M6_QTY =models.IntegerField(null=True,blank=True)
    TY_M7_QTY =models.IntegerField(null=True,blank=True)
    TY_M8_QTY =models.IntegerField(null=True,blank=True)
    TY_M9_QTY =models.IntegerField(null=True,blank=True)
    TY_M10_QTY =models.IntegerField(null=True,blank=True)
    TY_M11_QTY =models.IntegerField(null=True,blank=True)
    TY_M12_QTY =models.IntegerField(null=True,blank=True)
    TY_M1_Val =models.IntegerField(null=True,blank=True)
    TY_M2_Val =models.IntegerField(null=True,blank=True)
    TY_M3_Val =models.IntegerField(null=True,blank=True)
    TY_M4_Val =models.IntegerField(null=True,blank=True)
    TY_M5_Val =models.IntegerField(null=True,blank=True)
    TY_M6_Val =models.IntegerField(null=True,blank=True)
    TY_M7_Val =models.IntegerField(null=True,blank=True)
    TY_M8_Val =models.IntegerField(null=True,blank=True)
    TY_M9_Val =models.IntegerField(null=True,blank=True)
    TY_M10_Val =models.IntegerField(null=True,blank=True)
    TY_M11_Val =models.IntegerField(null=True,blank=True)
    TY_M12_Val =models.IntegerField(null=True,blank=True)
    CreatedDate =models.DateTimeField()
    CreatedBy=models.ForeignKey(ScmUser,on_delete=models.CASCADE)
    UpdatedDate=models.DateTimeField(auto_now=True)
    IPAddress=models.CharField(max_length=100,null=True,blank=True)




